import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import "./globals.css";

const geist = localFont({
  src: [
    { path: '../public/fonts/geist/Geist-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../public/fonts/geist/Geist-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../public/fonts/geist/Geist-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-geist',
})

const geistMono = localFont({
  src: [
    { path: '../public/fonts/geist/GeistMono-Regular.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-geist-mono',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${geistMono.variable} ${inter.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
